# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aYBlq7HaoyMdFdM2Dv7hkT-gyKabOHFl
"""

import random
from Data import*
def check_test():
  Test_Semester = input("Bài kiểm tra(Giữa khóa, cuối khóa,..): ")
  Subject = input("Bộ môn(PTS, BE, RBT...): ")
  
  Test_name = "Bài kiểm tra {} {}".format(Subject, Test_Semester)
  TotalScore = int(input("Nhập điểm tổng bài kiểm tra lý thuyết: "))
  student_score = int(input("Nhập điểm chấm bài của học sinh: "))
  student_str_score = str(student_score) + "/" + str(TotalScore)
  actual_percent = (student_score / TotalScore) * 100

  practical_total = int(input("Nhập điểm tổng bài kiểm tra thực hành: "))
  student_practical = int(input("Nhập điểm chấm bài thực hành của học sinh: "))
  student_str_practical_score = "{}/{}".format(str(student_practical), str(practical_total))
  practical_score = (student_practical / practical_total) * 100

  total_score = student_practical + student_score
  total = "{}/{}".format(str(student_practical + student_score), str(TotalScore + practical_total))
  
  return [Test_name, student_str_score, actual_percent, student_str_practical_score, practical_score, total, total_score]

def classify_grade(score):
  if score >= 80:
    result_grade = "Good"
  elif score < 80 and score >= 60:
    result_grade = "Average"
  elif score < 60 and score >= 50:
    result_grade = "Need Improvement"
  elif score < 50 and score > 0:
    result_grade = "Poor"
  
  return result_grade

def send_feedback(test_info, actual_percent, practical_score, total_score):
  
  student_name = input("Tên học sinh: ")
  print(str(test_info[0]))
  print("Điểm bài thi lý thuyết: ", str(test_info[1]))
  print("Tỉ lệ làm đúng: ", str(round(test_info[2], 2)), "%")
  result_grade = classify_grade(actual_percent)
  print("Kết quả của bạn là:", result_grade)

  # Feedback về bài kiểm tra lý thuyết
  print("\nTên học sinh: " + student_name)
  print("\nBÀI KIỂM TRA LÝ THUYẾT")
  feedback1 = random.choice(feedback_test[result_grade])
  feedback2 = random.choice(feedback_test[result_grade])
  print("Điểm bài kiểm tra lý thuyết: ", str(test_info[1]))
  print("Tỉ lệ làm đúng: ", str(round(test_info[2], 2)), "%")
  print(feedback1)
  print(feedback2)

  # Feedback về bài thực hành
  print("\nBÀI KIỂM TRA THỰC HÀNH")
  practical_grade = classify_grade(practical_score)
  feedback3 = random.choice(feedback_test[practical_grade])
  feedback4 = random.choice(feedback_test[practical_grade])
  print("Điểm bài thực hành: ", str(test_info[3]))
  print("Tỉ lệ làm đúng: ", str(round(test_info[4], 2)), "%")
  print(feedback3)
  print(feedback4)

  total_grade = classify_grade(test_info[6])
  feedback5 = random.choice(general_feedback[practical_grade])
  feedback6 = random.choice(general_feedback[practical_grade])
  print("\nĐiểm tổng kết bài kiểm tra giữa khóa: ", test_info[5])
  print("*Nhận xét của giáo viên về quá trình học:")
  print(feedback5)
  print(feedback6)

test_info = check_test()
actual_percent = test_info[2]
practical_score = test_info[4]
total_score = test_info[5]
send_feedback(test_info, actual_percent, practical_score, total_score)